# Checks if the links in Markdown files are valid using Linkspector.

name: Check links in Markdown files
on:
  pull_request:

jobs:
  check-links:
    name: Linkspector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Check .md links with linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review