name: Lint with ruff

on:
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/ruff-action@v3

      - name : Run ruff
        run: ruff check .

      - name: Install Taplo CLI
        run: |
          TAPLO_VERSION="0.8.1"
          curl -sSL "https://github.com/tamasfe/taplo/releases/download/${TAPLO_VERSION}/taplo-full-linux-x86_64.gz" -o taplo.gz
          gunzip taplo.gz
          chmod +x taplo
          mkdir -p "$HOME/.taplo/bin"
          mv taplo "$HOME/.taplo/bin/taplo"
          echo "$HOME/.taplo/bin" >> $GITHUB_PATH

      - name: Verify Taplo
        run: taplo --version

      - name: Check .toml formatting with Taplo
        run: taplo fmt --check
